import type { NextPage } from "next";
import { useSession, signIn } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const channels = trpc.useQuery(["question.getAllChannels"])
  const session = useSession()
  return (
    <>
      <Head>
        <title>Agora</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Agora <span className="text-purple-300">Demo</span>
        </h1>
        {session && session.data ?
          <>
            {channels.data ? <p>{channels.data.map(c => <p key={c.id}>- {c.name}</p>)}</p> : <p>Loading..</p>}
            {/* <p>{JSON.stringify(session)}</p> */}
            <Link href={'/create'}>
              <div>Create New</div>
            </Link>
          </>
          :
          <>
            {/* <p>{JSON.stringify(session)}</p> */}
            <div onClick={() => signIn()}>Login</div>
          </>
        }
      </main>
    </>
  );
};


export default Home;
